---

timezone: America/Los_Angeles
install_path: /opt
binary: jdk-8u231-linux-arm32-vfp-hflt.tar.gz
base_path: /usr/java
home: /usr/java/jdk1.8.0_231
password: $6$mysecretsalt$MIJffjeQyfrKKrGkprGrDL/g2mCJa53koLmYQuuLmY9y37pDvGKPXU1Ov3RbMi.tpQ9cWvxAzUVtBLe7KrZoU.

wifi:
  country: US
  ssid: test1
  psk: test1

gradle:
  binary: gradle-6.0.1-bin.zip
  home: /opt/gradle-6.0.1
  url: https://services.gradle.org/distributions/gradle-6.0.1-bin.zip
  checksum: sha256:d364b7098b9f2e58579a3603dc0a12a1991353ac58ed339316e6762b21efba44

maven:
  binary: apache-maven-3.6.3-bin.tar.gz
  home: /opt/apache-maven-3.6.3
  url: https://www-us.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  checksum: sha512:c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
