---

oracle_database_version: 11g
oracle_database_release: 11.2.0.4
oracle_database_edition: EE

# installers
oracle_database_installers_11_2_0_4_1of2: /opt/installer/linux.x64_11gR2_database_1of2.zip
oracle_database_installers_11_2_0_4_2of2: /opt/installer/linux.x64_11gR2_database_2of2.zip

# instance variables
oracle_database_sid: ORCL
oracle_database_global_name: ORCL
oracle_database_template_name: General_Purpose.dbc
oracle_database_admin_password: welcome1
oracle_database_auto_memory_mgnt: TRUE
oracle_database_memory_percentage: 80
oracle_database_memory_total: 1024
oracle_database_type: OLTP

# listener variables
oracle_database_listener_name: LISTENER
oracle_database_listener_port: 1521
# oracle_database_init_params: JAVA_JIT_ENABLED=FALSE

# Installer files can be downloaded from:
# File 1: https://download.oracle.com/otn/linux/oracle11g/R2/linux.x64_11gR2_database_1of2.zip
# File 2: https://download.oracle.com/otn/linux/oracle11g/R2/linux.x64_11gR2_database_2of2.zip

# Change /tmp to the actual path of the Oracle installer in the host machine
oracle_installer_path: /tmp

oracle_database_inventory_location: /home/oracle/oracle_inventory
oracle_database_oracle_base: /home/oracle/product
oracle_database_oracle_home: "{{ oracle_database_oracle_base }}/oracle_home"

os_swap_file: /swap1.swap
